Update brief.md
GroupLima/SAR-Repo pull request #32
Opened 2024-10-13 17:57 UTC by piotresh

additional descriptions <3

2024-10-13 18:11 UTC, caitlinthaeler requested changes
You misspelled building in the php definition

2024-10-13 18:19 UTC, caitlinthaeler approved these changes
good job

2024-10-14 14:25 UTC, hothbert commented
Conflicts resolved

2024-10-14 14:26 UTC, hothbert approved these changes

2024-10-14 15:27 UTC, caitlinthaeler approved these changes

2024-10-14 15:27 UTC, merged